version: '3'

services:
  rethinkdb:
    image: loopback-rethinkdb
    ports:
      - "38080:8080"
    volumes:
      - ./data:/data
    command: rethinkdb --bind all

  api:
    image: loopback-api
    environment:
      NODE_ENV: development
    ports:
      - 3002:3000
    volumes:
      - .:/usr/src/api
    command: node .
    depends_on:
      - rethinkdb
