version: '3.5'

services:
  api:
    image: loopback-api
    environment:
      NODE_ENV: development
    ports:
      - 3002:3000  # map our machines port 3002 with port 3000 in the container
    volumes:
      - .:/usr/src/api  # map this current directory with /usr/src/api in the docker container
    command: nodemon .

  mongodb:
    image: loopback-mongo
    environment:
      MONGODB_USER: "${user}" 
      MONGODB_PASS: "${pass}"
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      SECRET_KEY_BASE: secret
      MONGO_URL: mongodb://mongo:27017/app_development
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet


# docker-compose run api slc loopback
# docker-compose run api yarn
# docker-compose up
# docker-compose exec mysqlDB mysql -u devuser -p

# docker-compose up -d
# docker-compose logs -f
# docker-compose logs -f api
# docker-compose exec api yarn add loopback-connector-mysql
